# Generated by Django 5.0.3 on 2024-03-15 15:09

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.CharField(max_length=128)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.tag')),
            ],
        ),
    ]
