# Generated by Django 5.0.3 on 2024-03-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=200)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
