# Generated by Django 5.0.3 on 2024-03-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='media',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(null=True, upload_to='gallery', verbose_name=''),
        ),
    ]
