# Generated by Django 5.0.3 on 2024-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0008_contact_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
